apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gym

resources:
  - namespace.yaml
  - app-config.yaml
  - app-secrets.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
